#!/bin/python3

flairClasses = [
	'android',
	'apple',
	'arch',
	'backtrack',
	'centos',
	'chakra',
	'debian',
	'dragonflybsd',
	'fedora',
	'freebsd',
	'gentoo',
	'gnome',
	'kde',
	'kubuntu',
	'linuxfromscratch',
	'linuxmint',
	'mandriva',
	'meego',
	'mepis',
	'netbsd',
	'nexeta',
	'openbsd',
	'opensuse',
	'pardus',
	'pcbsd',
	'pclinuxos',
	'redhat',
	'sabanyon',
	'aptosid',
	'slackware',
	'slax',
	'solaris',
	'tux',
	'ubuntu',
	'ultamate',
	'vector',
	'windows',
	'xandros',
	'yellowdog',
	'enlightenment',
	'fluxbox',
	'freedesktop',
	'freesoftwarefoundation',
	'gnu',
	'konsole',
	'openbox',
	'xfce',
	'xorg',
	'irix',
	'kdeneon',
	'maui',
	'manjaro',
]

cssRules = []

for i, flairClass in enumerate(flairClasses):
	px = '0' if i == 0 else str(i * -16)
	cssRule = ".flair-" + flairClass + " { background-position: 0px " + px + "px; }"
	cssRules.append(cssRule)

cssRules = sorted(cssRules)
for cssRule in cssRules:
	print(cssRule)
